### ISSUE TITLE
libbgs.so Undefined reference to OpenCV functions

### ISSUE THREAD

**Issue by dasguptar** [andrewssobral/bgslibrary#5]
On attempting to build on Ubuntu 12.04 with OpenCV 2.4.8, the make command runs into an error when trying to link the relevant libraries:

```
[ 97%] Built target bgs
Linking CXX executable bgs
libbgs.so: undefined reference to `int cv::CommandLineParser::analyzeValue<int>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
libbgs.so: undefined reference to `cv::Algorithm::_create(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libbgs.so: undefined reference to `cv::BackgroundSubtractor::getBackgroundImage(cv::_OutputArray const&) const'
libbgs.so: undefined reference to `cv::CommandLineParser::has(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libbgs.so: undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
libbgs.so: undefined reference to `cv::Mat::operator _IplImage() const'
libbgs.so: undefined reference to `cv::split(cv::Mat const&, std::vector<cv::Mat, std::allocator<cv::Mat> >&)'
libbgs.so: undefined reference to `cv::Exception::Exception(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
libbgs.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> > cv::CommandLineParser::analyzeValue<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
libbgs.so: undefined reference to `cv::imshow(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
libbgs.so: undefined reference to `cv::BackgroundSubtractorMOG::BackgroundSubtractorMOG()'
libbgs.so: undefined reference to `cv::putText(cv::Mat&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
libbgs.so: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
libbgs.so: undefined reference to `cv::BackgroundSubtractorMOG2::BackgroundSubtractorMOG2()'
libbgs.so: undefined reference to `cv::findContours(cv::_OutputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)'
libbgs.so: undefined reference to `cv::BackgroundSubtractorMOG2::getBackgroundImage(cv::_OutputArray const&) const'
libbgs.so: undefined reference to `bool cv::CommandLineParser::get<bool>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
libbgs.so: undefined reference to `cv::CommandLineParser::printParams()'
libbgs.so: undefined reference to `cv::imread(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
libbgs.so: undefined reference to `cv::Mat::Mat(_IplImage const*, bool)'
libbgs.so: undefined reference to `cv::CommandLineParser::CommandLineParser(int, char const* const*, char const*)'
libbgs.so: undefined reference to `cv::drawContours(cv::_OutputArray const&, cv::_InputArray const&, int, cv::Scalar_<double> const&, int, int, cv::_InputArray const&, int, cv::Point_<int>)'
libbgs.so: undefined reference to `cv::CommandLineParser::getString(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: ld returned 1 exit status
make[2]: *** [bgs] Error 1
make[1]: *** [CMakeFiles/bgs_bin.dir/all] Error 2
make: *** [all] Error 2
```
