### ISSUE TITLE
Doesn't compile with clang 4.2 on mac osx

### ISSUE THREAD

**Issue by osiloke** [andrewssobral/bgslibrary#19]
Cannot compile with clang on mac osx because of misplaced headers. For example,

```
bgslibrary/package_bgs/pl/DistanceUtils.h:190:68: error: no template named 'enable_if' in namespace 'std'; did you mean
      '__gnu_cxx::__enable_if'?
/Users/osilokee/workspace/startups/traffic/bgslibrary/package_bgs/pl/DistanceUtils.h:190:83: error: no template named 'is_floating_point' in namespace 'std'; did you mean
      '::std::tr1::is_floating_point'?
```

Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin11.4.2
Thread model: posix
